version: '3'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: client.dockerfile
    depends_on: 
      - server
    tty: true
    volumes:
      - ./client:/app

  server:
    container_name: server
    build:
      context: .
      dockerfile: server.dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_PORT=$POSTGRES_PORT
    depends_on: 
      - db
    tty: true
    volumes:
      - ./server:/app

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - $PROXY_PORT:$PROXY_PORT
    depends_on:
      - client
    volumes:
      - ./proxy:/etc/nginx/conf.d/

  faker:
    container_name: faker
    build:
      context: .
      dockerfile: faker.dockerfile
    ports:
      - $FAKER_PORT:$FAKER_PORT
    volumes:
      - ./server/graph:/workdir